### PR TITLE
CI with Github Actions

### PR DESCRIPTION
**Pull request by shamazmazum**
Hi! This commit adds CI tests for SBCL clisp and CCL on Linux. Do not know how to add macos. You can use this as a temporary solution.

### CODE REVIEW

**Comment by shamazmazum** [comment]
Here is how it looks like:

https://github.com/shamazmazum/ip-interfaces/actions/runs/463577609

**Comment by elliottslaughter** [comment]
Thanks for doing this! I will try to take a look over the next couple of days.

**Review by adlai — COMMENTED** [review]
Excellent initiative, @shamazmazum ! Thank you for making this PR, and the other similar ones; have you documented your cl-cirrus project in any detail beyond [the example](https://github.com/shamazmazum/cl-cirrus#example)?

**Comment by shamazmazum** [comment]
@adlai, no, unfortunately. Also please note, that the name cl-cirrus is misleading. There is a second branch on that repo, called github-actions, which contains installation script called `install-actions.sh` which I use in this pull request. CirrusCI is for testing on FreeBSD (they provide FreeBSD images).

Both `install.sh` and `install-actions.sh` download and install [CIM](https://github.com/sionescu/CIM) which is outdated as its author says, but simply works. In new project the author recommends to use roswell.

**Comment by adlai** [comment]
> @adlai, no, unfortunately. Also please note, that the name cl-cirrus is misleading. There is a second branch on that repo, called github-actions, which contains installation script called `install-actions.sh` which I use in this pull request. CirrusCI is for testing on FreeBSD (they provide FreeBSD images).

Thank you for the explanation.

> Both `install.sh` and `install-actions.sh` download and install [CIM](https://github.com/sionescu/CIM) which is outdated as its author says, but simply works. In new project the author recommends to use roswell.

I have no fundamental problem with using old programs, although I think that the current Travis-CI script already uses Roswell.

> Personally, I still use CIM and usually have CirrusCI and Github Actions on the same repo, like [here](https://github.com/shamazmazum/similar-images), but if you have time to learn, you can replace CIM with more modern alternative. See [here](https://github.com/cl-doc-systems/codex/blob/main/.github/workflows/docs.yml) how roswell can be used.

Thank you for linking directly to the docs. You have saved me quite a bit of searching around!

**Comment by elliottslaughter** [comment]
Sorry for taking so long to get back to this.

I eventually decided to go a different route that's more similar what I original had for Travis (based on Roswell, which gives me access to more Lisp implementations). That is now in master, so I will close this PR.

Thanks again for taking the effort to do this, and looks like your project might be a good basis for others looking to get off the ground on CI.

**Pull request closed without merging**
